# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78bc253984e1323caf92a00ce89b1d8bc252f08f04abee52a6f353ed7e45d6a45988c3c60bfd5902e27e94cf19f136e334346cb079f089b7b035678035513bb7

test:
  secret_key_base: 3b9e77d2afc223077be86c2cdedf74b53a4ef76bfddb7287745b5455bde612d121f977c52b6e409d02114dd821a6304c584ca28e0a01116fb101d93f91ea586b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
